export const techMap: { [key: string]: string } = {
  javaScript: "devicon-javascript-plain",
  js: "devicon-javascript-plain colored",
  react: "devicon-react-original",
  reactjs: "devicon-react-original",
  nextjs: "devicon-nextjs-original",
  typescript: "devicon-typescript-plain",
  ts: "devicon-typescript-plain colored",
  python: "devicon-python-plain",
  django: "devicon-django-plain",
  flask: "devicon-flask-original",
  html: "devicon-html5-plain",
  css: "devicon-css3-plain",
  tailwindcss: "devicon-tailwindcss-plain",
  nodejs: "devicon-nodejs-plain",
  express: "devicon-express-original",
  mongodb: "devicon-mongodb-plain",
  mysql: "devicon-mysql-plain",
  postgresql: "devicon-postgresql-plain",
  git: "devicon-git-plain",
  github: "devicon-github-original",
  docker: "devicon-docker-plain",
  kubernetes: "devicon-kubernetes-plain",
  aws: "devicon-amazonwebservices-plain",
  azure: "devicon-azure-plain",
  gcp: "devicon-googlecloud-plain",
  java: "devicon-java-plain",
  csharp: "devicon-csharp-plain",
  php: "devicon-php-plain",
  ruby: "devicon-ruby-plain",
  rails: "devicon-rails-plain",
  go: "devicon-go-plain",
};
